export const config = {
  env: {
    NODE_ENV: process.env.NODE_ENV!,
    NEXT_PUBLIC_URL: process.env.NEXT_PUBLIC_URL!,
    NEXT_PUBLIC_API_ENDPOINT: process.env.NEXT_PUBLIC_API_ENDPOINT!,
    NEXT_PUBLIC_PROD_API_ENDPOINT: process.env.NEXT_PUBLIC_PROD_API_ENDPOINT!,
    imagekit: {
      NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY: process.env.NEXT_PUBLIC_IMAGEKIT_PUBLIC_KEY!,
      NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT: process.env.NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT!,
      IMAGEKIT_PRIVATE_KEY: process.env.IMAGEKIT_PRIVATE_KEY!,
    },
    FACEBOOK_CLIENT_ID: process.env.FACEBOOK_CLIENT_ID!,
    FACEBOOK_CLIENT_SECRET: process.env.FACEBOOK_CLIENT_SECRET!,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID!,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET!,
    DATABASE_URL: process.env.DATABASE_URL!,
    upstash: {
      UPSTASH_REDIS_URL: process.env.UPSTASH_REDIS_URL!,
      UPSTASH_REDIS_TOKEN: process.env.UPSTASH_REDIS_TOKEN!,
      QSTASH_URL: process.env.QSTASH_URL!,
      QSTASH_TOKEN: process.env.QSTASH_TOKEN!,
    },
    RESEND_API_KEY: process.env.RESEND_API_KEY!,
    STREAM_API_KEY: process.env.STREAM_API_KEY!,
    STREAM_API_SECRET: process.env.STREAM_API_SECRET!,
  },
};
